"""CRM Pydantic schemas package."""

from app.schemas.crm.accounts_contacts import (
    CrmAccountCreate,
    CrmAccountListResponse,
    CrmAccountRead,
    CrmAccountUpdate,
    CrmContactCreate,
    CrmContactListResponse,
    CrmContactRead,
    CrmContactUpdate,
)
from app.schemas.crm.activities_notes import (
    CrmActivityCreate,
    CrmActivityListResponse,
    CrmActivityRead,
    CrmActivityUpdate,
    CrmNoteCreate,
    CrmNoteListResponse,
    CrmNoteRead,
    CrmNoteUpdate,
    CrmTimelineEventRead,
    CrmTimelineListResponse,
)
from app.schemas.crm.automations import (
    CrmAutomationRuleCreate,
    CrmAutomationRuleListResponse,
    CrmAutomationRuleRead,
    CrmAutomationRuleUpdate,
)
from app.schemas.crm.api_keys import (
    CrmApiKeyCreate,
    CrmApiKeyCreated,
    CrmApiKeyListResponse,
    CrmApiKeyRead,
    InboundLeadCreate,
    InboundLeadResponse,
)
from app.schemas.crm.deals import (
    CrmDealCloseRequest,
    CrmDealCreate,
    CrmDealListResponse,
    CrmDealMoveStageRequest,
    CrmDealRead,
    CrmDealUpdate,
)
from app.schemas.crm.pipelines import (
    CrmPipelineCreate,
    CrmPipelineRead,
    CrmPipelineUpdate,
    CrmStageCreate,
    CrmStageRead,
    CrmStageReorderItem,
    CrmStageReorderRequest,
    CrmStageUpdate,
)
from app.schemas.crm.settings import CrmSettingRead, CrmSettingUpdate
from app.schemas.crm.tags_fields import (
    CrmCustomFieldCreate,
    CrmCustomFieldListResponse,
    CrmCustomFieldRead,
    CrmCustomFieldUpdate,
    CrmTagCreate,
    CrmTagListResponse,
    CrmTagRead,
    CrmTagUpdate,
)

__all__ = [
    "CrmAccountCreate",
    "CrmAccountListResponse",
    "CrmAccountRead",
    "CrmAccountUpdate",
    "CrmActivityCreate",
    "CrmActivityListResponse",
    "CrmActivityRead",
    "CrmActivityUpdate",
    "CrmApiKeyCreate",
    "CrmApiKeyCreated",
    "CrmApiKeyListResponse",
    "CrmApiKeyRead",
    "CrmAutomationRuleCreate",
    "CrmAutomationRuleListResponse",
    "CrmAutomationRuleRead",
    "CrmAutomationRuleUpdate",
    "CrmContactCreate",
    "CrmContactListResponse",
    "CrmContactRead",
    "CrmContactUpdate",
    "CrmCustomFieldCreate",
    "CrmCustomFieldListResponse",
    "CrmCustomFieldRead",
    "CrmCustomFieldUpdate",
    "CrmDealCloseRequest",
    "CrmDealCreate",
    "CrmDealListResponse",
    "CrmDealMoveStageRequest",
    "CrmDealRead",
    "CrmDealUpdate",
    "CrmNoteCreate",
    "CrmNoteListResponse",
    "CrmNoteRead",
    "CrmNoteUpdate",
    "CrmPipelineCreate",
    "CrmPipelineRead",
    "CrmPipelineUpdate",
    "CrmSettingRead",
    "CrmSettingUpdate",
    "CrmStageCreate",
    "CrmStageRead",
    "CrmStageReorderItem",
    "CrmStageReorderRequest",
    "CrmStageUpdate",
    "CrmTagCreate",
    "CrmTagListResponse",
    "CrmTagRead",
    "CrmTagUpdate",
    "CrmTimelineEventRead",
    "CrmTimelineListResponse",
    "InboundLeadCreate",
    "InboundLeadResponse",
]
